const catalogueFilterData = {
  organizations: [
    "01 AI",
    "Adept",
    "Adobe",
    "AI2",
    "AI21 Labs",
    "Aleph Alpha",
    "Alibaba",
    "Amazon",
    "Anthropic",
    "Apple",
    "Argilla",
    "Argonne National Laboratory",
    "AssemblyAI",
    "Avignon University, Nantes University",
    "Baichuan Inc.",
    "Baidu",
    "Baidu, PengCheng Laboratory",
    "Beijing Academy of Artificial Intelligence",
    "Beijing Academy of Artificial Intelligence, Tsinghua University",
    "Beijing Academy of Artificial Intelligence, University of Science and Technology of China",
    "Beijing Institute of Technology",
    "Berkeley",
    "BigCode",
    "BigScience",
    "Bloomberg",
    "Boston University",
    "ByteDance",
    "ByteDance, Tsinghua University",
    "Cagliostro Research Lab",
    "Carnegie Mellon University",
    "Carnegie Mellon University, University of Pennsylvania",
    "CausalLM",
    "Cerebras",
    "ChatGLM",
    "Cognition Labs",
    "Cognitive Computations",
    "Cohere",
    "Cohere for AI, Cohere, Brown University, Carnegie Mellon University, MIT",
    "Columbia",
    "Columbia, Apple AI",
    "Cornell University, Mosaic",
    "Cresta",
    "DAMO Academy, Alibaba",
    "Databricks",
    "Deci",
    "Deepnight Research",
    "Deepseek AI",
    "Eleuther AI",
    "EleutherAI",
    "EPFL, Idiap Research Institute, OpenAssistant, Yale",
    "FuseAI",
    "Google",
    "Google Deepmind",
    "GreenBit AI",
    "H2O AI",
    "Hong Kong University of Science and Technology (Guangzhou + original), Beijing Academy of Artificial Intelligence",
    "Hugging Face",
    "HuggingFace",
    "IBM",
    "Ideogram AI",
    "Inception Institute of Artificial Intelligence, Cerebras, Mohamed bin Zayed University of Artificial Intelligence",
    "Inflection AI",
    "Institute of Automation Chinese Academy of Sciences",
    "International Digital Economy Academy, South China University of Technology, University of Science and Technology of China",
    "InternLM",
    "Konan",
    "Kotoba Tech",
    "KT Corporation",
    "Kunlun Inc.",
    "LAION",
    "Lehigh University",
    "LG AI Research",
    "LLM360",
    "LMSYS",
    "Maya Philippines",
    "Meta",
    "Meta, CMU, TTI-Chicago, UC Berkeley, University of Washington",
    "Microsoft",
    "Microsoft, NVIDIA",
    "Mistral AI",
    "Moreh",
    "Morgan Stanley, ServiceNow Research, University of Montreal, Mila-Quebec AI Institute",
    "Mosaic",
    "Nanyang Technological University",
    "National University of Singapore",
    "National University of Singapore, University of Edinburgh, ETH Zurich",
    "NAVER",
    "NCSOFT",
    "Neeva",
    "Nous",
    "Nous Research",
    "Nous Research, EleutherAI, University of Geneva",
    "Nucleus.AI",
    "NVIDIA",
    "NVIDIA, Stanford",
    "Ohio State University",
    "Ollama",
    "Open X-Embodiment, Google Deepmind",
    "OpenAI",
    "OpenAssistant",
    "OpenBMB",
    "OpenLemur",
    "OrionStarAI",
    "Peking University Institute for Artificial Intelligence",
    "Princeton University, Eleuther AI",
    "Qwen Team",
    "Rakuten",
    "Reka",
    "RWKV",
    "Salesforce",
    "Samba Nova Systems",
    "SciPhi",
    "Shanghai AI Laboratory",
    "Shanghai AI Laboratory, Nanjing University, Zhejiang University",
    "SK Telecom",
    "Soochow University",
    "Stability AI",
    "Stanford",
    "Suno",
    "TigerResearch",
    "Together",
    "Tokyo Institute of Technology, MIT-IBM Watson Lab, Sapienza University of Rome",
    "Toyota Research Institute",
    "Tsinghua University",
    "Twelve Labs",
    "UAE Technology Innovation Institute",
    "University of Turku, HuggingFace, National Library of Finland",
    "University of Washington",
    "University of Washington, Spotify",
    "VAGO Solutions",
    "Virtual Interactive",
    "Wayve",
    "Writer",
    "xAI",
    "Xverse",
    "Xwin",
    "Yandex",
    "You",
    "Zhejiang University",
    "Zhipu AI, Tsinghua University",
  ],
  licences: [
    "AI2 ImpACT",
    "Apache 2.0",
    "Apple",
    "BigCode Open Rail-M",
    "BigCode Open RAIL-M v1",
    "BigCode Open RAIL-M v1.0",
    "BigCode OpenRail-M",
    "BigScience RAIL v1.0",
    "bigscience-bloom-rail-1.0",
    "BSD-3-Clause",
    "CC BY 4.0",
    "CC BY NC 4.0",
    "CC BY NC 4.0 (model weights)",
    "CC BY-NC 4.0",
    "CC by-NC-SA 4.0",
    "CC-BY-NC 4.0",
    "CC-BY-NC-4.0",
    "custom",
    "Databricks Open Model License",
    "Fair AI Public License 1.0-SD",
    "GLM-130B License",
    "LLaMA 2",
    "Llama 3",
    "LLaMa License (model weights), GPLv3 (code)",
    "LLaMA2",
    "MIT",
    "Modified MIT License",
    "Noncommercial Use License",
    "none (model weights), BSD-3-Clause (code)",
    "OpenRail++",
    "OPT-175B License",
    "OPT-IML 175B License",
    "StabilityAI Non-Commercial Research Community License",
  ],
  access: ["closed", "limited", "open"],
  modalities: [
    "amino acid sequence",
    "protein structure",
    "audio",
    "image",
    "text",
    "video",
    "code",
  ],
};

export default catalogueFilterData;
